[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mazegen"
version = "1.0.0"
description = "Reusable maze generator module for A_Maze_ing project."
readme = "mazegen_package/README.md"
requires-python = ">=3.13.1"

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13.1",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["mazegen_package*"]